-- =============================================================================
-- SmartPoultry API — Seed Data
-- =============================================================================
-- Inserts default admin user, a demo farm, blocks, pens, and sample records.
-- Safe to run multiple times — all inserts use ON CONFLICT DO NOTHING.
--
-- Prerequisites:
--   • schema.sql must have been applied first.
--   • The hashed_password below is the Argon2 hash of "Admin@1234!"
--     generated by passlib with the argon2 scheme.
--     To regenerate:
--       python3 -c "from passlib.context import CryptContext; \
--                   ctx = CryptContext(schemes=['argon2']); \
--                   print(ctx.hash('Admin@1234!'))"
--
-- Usage:
--   psql "$DATABASE_URL" -f backend/sql/seed_data.sql
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Default admin user
--    Password: Admin@1234!
--    Change this immediately after first login.
-- ---------------------------------------------------------------------------
INSERT INTO users (
    full_name,
    email,
    hashed_password,
    role,
    is_active,
    contact,
    country,
    city,
    bio,
    created_at
)
VALUES (
    'System Administrator',
    'admin@smartpoultry.com',
    -- Argon2 hash of "Admin@1234!" — regenerate before production use
    '$argon2id$v=19$m=65536,t=3,p=4$placeholder_hash_replace_me$placeholder_hash_replace_me',
    'admin',
    TRUE,
    '+1-000-000-0000',
    'Kenya',
    'Nairobi',
    'Default system administrator. Change password on first login.',
    now()
)
ON CONFLICT (email) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Demo farm  (owned by the admin user)
-- ---------------------------------------------------------------------------
INSERT INTO farms (
    name,
    owner_id,
    plan,
    is_active,
    trial_used,
    trial_start,
    trial_end,
    created_at
)
SELECT
    'Green Valley Poultry Farm',
    u.id,
    'free_trial',
    TRUE,
    TRUE,
    now(),
    now() + INTERVAL '30 days',
    now()
FROM users u
WHERE u.email = 'admin@smartpoultry.com'
  AND NOT EXISTS (
      SELECT 1 FROM farms f WHERE f.owner_id = u.id
  );

-- Link admin user → farm
UPDATE users u
SET    farm_id = f.id
FROM   farms f
WHERE  f.owner_id = u.id
  AND  u.email    = 'admin@smartpoultry.com'
  AND  u.farm_id  IS NULL;

-- ---------------------------------------------------------------------------
-- 3. Blocks (housing sections)
-- ---------------------------------------------------------------------------
INSERT INTO blocks (name, farm_id, created_at)
SELECT 'Block A', f.id, now()
FROM   farms f
JOIN   users u ON u.id = f.owner_id
WHERE  u.email = 'admin@smartpoultry.com'
ON CONFLICT (farm_id, name) DO NOTHING;

INSERT INTO blocks (name, farm_id, created_at)
SELECT 'Block B', f.id, now()
FROM   farms f
JOIN   users u ON u.id = f.owner_id
WHERE  u.email = 'admin@smartpoultry.com'
ON CONFLICT (farm_id, name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. Pens
-- ---------------------------------------------------------------------------

-- Pen A1 — deep litter, Block A
INSERT INTO pens (
    name, capacity, status, farm_id, user_id, block_id,
    start_date, housing_system, breed, batch_name, source_hatchery,
    initial_birds, current_birds, floor_area_sq_m, max_density,
    litter_type, feeder_count, waterer_count, nest_count,
    mortality_last_7d, created_at
)
SELECT
    'Pen A1', 500, 'active', f.id, u.id, ba.id,
    now() - INTERVAL '120 days',
    'deep_litter', 'Lohmann Brown', 'Batch-2024-01', 'Kenchic Hatchery',
    500, 492, 50.0, 10.0,
    'wood_shavings', 10, 8, 25,
    2, now()
FROM   users  u
JOIN   farms  f  ON f.owner_id = u.id
JOIN   blocks ba ON ba.farm_id = f.id AND ba.name = 'Block A'
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM pens p WHERE p.farm_id = f.id AND p.name = 'Pen A1'
  );

-- Pen A2 — deep litter, Block A
INSERT INTO pens (
    name, capacity, status, farm_id, user_id, block_id,
    start_date, housing_system, breed, batch_name, source_hatchery,
    initial_birds, current_birds, floor_area_sq_m, max_density,
    litter_type, feeder_count, waterer_count, nest_count,
    mortality_last_7d, created_at
)
SELECT
    'Pen A2', 500, 'active', f.id, u.id, ba.id,
    now() - INTERVAL '90 days',
    'deep_litter', 'Lohmann Brown', 'Batch-2024-02', 'Kenchic Hatchery',
    500, 488, 50.0, 10.0,
    'rice_husks', 10, 8, 25,
    3, now()
FROM   users  u
JOIN   farms  f  ON f.owner_id = u.id
JOIN   blocks ba ON ba.farm_id = f.id AND ba.name = 'Block A'
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM pens p WHERE p.farm_id = f.id AND p.name = 'Pen A2'
  );

-- Pen B1 — cage system, Block B
INSERT INTO pens (
    name, capacity, status, farm_id, user_id, block_id,
    start_date, housing_system, breed, batch_name, source_hatchery,
    initial_birds, current_birds,
    cell_length_mm, cell_width_mm, cell_height_mm,
    birds_per_cell, tiers_per_set, cells_per_set,
    mortality_last_7d, created_at
)
SELECT
    'Pen B1', 300, 'active', f.id, u.id, bb.id,
    now() - INTERVAL '60 days',
    'cage', 'ISA Brown', 'Batch-2024-03', 'Sasso Hatchery',
    300, 297,
    450, 500, 400,
    4, 3, 10,
    1, now()
FROM   users  u
JOIN   farms  f  ON f.owner_id = u.id
JOIN   blocks bb ON bb.farm_id = f.id AND bb.name = 'Block B'
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM pens p WHERE p.farm_id = f.id AND p.name = 'Pen B1'
  );

-- ---------------------------------------------------------------------------
-- 5. Sample production records — last 7 days for Pen A1
-- ---------------------------------------------------------------------------
INSERT INTO production_records (
    date, pen_id, farm_id, age_days, week_number,
    opening_stock, closing_stock, mortality, feed_kg,
    good_eggs, damaged_eggs, small_eggs,
    double_yolk_eggs, soft_shell_eggs, shells, broody_hen, culls,
    total_eggs, hd_percentage, er_ratio,
    recorded_by_id, staff_name, created_at
)
SELECT
    (now() - INTERVAL '7 days' + (n || ' days')::INTERVAL)::TIMESTAMP,
    p.id,
    f.id,
    120 + n,
    ROUND(((120 + n) / 7.0)::NUMERIC, 1),
    492, 492, 0,
    ROUND((492 * 0.12)::NUMERIC, 1),
    440 + n * 2, 3, 2,
    0, 0, 0, 0, 0,
    (440 + n * 2) + 3 + 2,
    ROUND((((440 + n * 2) + 5) / 492.0 * 100)::NUMERIC, 2),
    ROUND(((492 * 0.12) / ((440 + n * 2) + 5))::NUMERIC, 3),
    u.id,
    u.full_name,
    now()
FROM   generate_series(0, 6) AS gs(n)
CROSS  JOIN users  u
JOIN   farms  f ON f.owner_id = u.id
JOIN   pens   p ON p.farm_id  = f.id AND p.name = 'Pen A1'
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
    SELECT 1 FROM production_records pr WHERE pr.pen_id = p.id
);

-- ---------------------------------------------------------------------------
-- 6. Egg inventory snapshot
-- ---------------------------------------------------------------------------
INSERT INTO egg_inventory (
    date, farm_id, opening_stock, received, sold, rejects, breakages, closing_stock
)
SELECT
    now(), f.id,
    0, 3080, 2800, 42, 18, 220
FROM   users u
JOIN   farms f ON f.owner_id = u.id
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM egg_inventory ei WHERE ei.farm_id = f.id
  );

-- ---------------------------------------------------------------------------
-- 7. Feed inventory
-- ---------------------------------------------------------------------------
INSERT INTO feed_inventory (feed_type, farm_id, opening_stock, received, consumed, closing_stock)
SELECT v.feed_type, f.id, v.opening, v.received, v.consumed, v.opening + v.received - v.consumed
FROM   users u
JOIN   farms f ON f.owner_id = u.id
CROSS  JOIN (VALUES
    ('Layer Mash',  500.0, 2000.0, 1800.0),
    ('Grower Mash', 200.0,  800.0,  750.0),
    ('Chick Mash',  100.0,  400.0,  380.0)
) AS v(feed_type, opening, received, consumed)
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM feed_inventory fi WHERE fi.farm_id = f.id
  );

-- ---------------------------------------------------------------------------
-- 8. Feed ingredients
-- ---------------------------------------------------------------------------
INSERT INTO feed_ingredients (farm_id, name, stock_kg, unit_cost, created_at)
SELECT f.id, v.name, v.stock_kg, v.unit_cost, now()
FROM   users u
JOIN   farms f ON f.owner_id = u.id
CROSS  JOIN (VALUES
    ('Maize',          1200.0, 0.35),
    ('Soybean Meal',    400.0, 0.65),
    ('Limestone',       150.0, 0.08),
    ('Premix (Layer)',   50.0, 2.50),
    ('Salt',             20.0, 0.05)
) AS v(name, stock_kg, unit_cost)
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM feed_ingredients fi WHERE fi.farm_id = f.id
  );

-- ---------------------------------------------------------------------------
-- 9. Sample feed mix + items
-- ---------------------------------------------------------------------------
INSERT INTO feed_mixes (farm_id, name, mix_date, total_kg, cost_per_kg, created_by, created_at)
SELECT f.id, 'Standard Layer Mix', now() - INTERVAL '3 days', 100.0, 0.42, u.id, now()
FROM   users u
JOIN   farms f ON f.owner_id = u.id
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM feed_mixes fm WHERE fm.farm_id = f.id
  );

INSERT INTO feed_mix_items (mix_id, ingredient_id, quantity_kg)
SELECT m.id, i.id, v.qty
FROM   users u
JOIN   farms f  ON f.owner_id = u.id
JOIN   feed_mixes m ON m.farm_id = f.id AND m.name = 'Standard Layer Mix'
JOIN   feed_ingredients i ON i.farm_id = f.id
CROSS  JOIN (VALUES
    ('Maize',          60.0),
    ('Soybean Meal',   25.0),
    ('Limestone',       8.0),
    ('Premix (Layer)',  5.0),
    ('Salt',            2.0)
) AS v(ingredient_name, qty)
WHERE  u.email = 'admin@smartpoultry.com'
  AND  i.name  = v.ingredient_name
  AND  NOT EXISTS (
      SELECT 1 FROM feed_mix_items fmi WHERE fmi.mix_id = m.id
  );

-- ---------------------------------------------------------------------------
-- 10. Tray inventory
-- ---------------------------------------------------------------------------
INSERT INTO tray_inventory (date, farm_id, opening_stock, received, sold, closing_stock)
SELECT now(), f.id, 50, 200, 180, 70
FROM   users u
JOIN   farms f ON f.owner_id = u.id
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM tray_inventory ti WHERE ti.farm_id = f.id
  );

-- ---------------------------------------------------------------------------
-- 11. Sample tray sale
-- ---------------------------------------------------------------------------
INSERT INTO tray_sales (
    customer_name, trays, price_per_tray, currency, total_price,
    sale_date, farm_id, recorded_by_id, created_at
)
SELECT
    'Nairobi Fresh Market', 50, 4.50, 'USD', 225.00,
    now() - INTERVAL '1 day', f.id, u.id, now()
FROM   users u
JOIN   farms f ON f.owner_id = u.id
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM tray_sales ts WHERE ts.farm_id = f.id
  );

-- ---------------------------------------------------------------------------
-- 12. Welcome notification
-- ---------------------------------------------------------------------------
INSERT INTO notifications (user_id, farm_id, message, read, created_at)
SELECT
    u.id, f.id,
    'Welcome to SmartPoultry! Your farm has been set up with demo data. '
    'Start by exploring the dashboard, then add your own pens and records.',
    FALSE,
    now()
FROM   users u
JOIN   farms f ON f.owner_id = u.id
WHERE  u.email = 'admin@smartpoultry.com'
  AND  NOT EXISTS (
      SELECT 1 FROM notifications n WHERE n.farm_id = f.id
  );

COMMIT;

-- =============================================================================
-- Verification queries (run manually to confirm seed data)
-- =============================================================================
-- SELECT 'users'              AS tbl, COUNT(*) FROM users;
-- SELECT 'farms'              AS tbl, COUNT(*) FROM farms;
-- SELECT 'blocks'             AS tbl, COUNT(*) FROM blocks;
-- SELECT 'pens'               AS tbl, COUNT(*) FROM pens;
-- SELECT 'production_records' AS tbl, COUNT(*) FROM production_records;
-- SELECT 'egg_inventory'      AS tbl, COUNT(*) FROM egg_inventory;
-- SELECT 'feed_inventory'     AS tbl, COUNT(*) FROM feed_inventory;
-- SELECT 'feed_ingredients'   AS tbl, COUNT(*) FROM feed_ingredients;
-- SELECT 'feed_mixes'         AS tbl, COUNT(*) FROM feed_mixes;
-- SELECT 'feed_mix_items'     AS tbl, COUNT(*) FROM feed_mix_items;
-- SELECT 'tray_inventory'     AS tbl, COUNT(*) FROM tray_inventory;
-- SELECT 'tray_sales'         AS tbl, COUNT(*) FROM tray_sales;
-- SELECT 'notifications'      AS tbl, COUNT(*) FROM notifications;
