# Alembic Configuration File

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

[sqlalchemy]
sqlalchemy.url = driver://user:pass@localhost/dbname

[alembic]
script_location = alembic
sqlalchemy.url = 
prepend_sys_path = .
version_path_separator = :
version_locations = %(here)s/versions
file_template = %%(rev)s_%%(slug)s
sourceless = false
sqlalchemy_module_prefix = sqlalchemy.sql
render_as_batch = true

[post_write_hooks]