"""add_missing_user_fields

Revision ID: daea903fc013
Revises: b3b3fe0e9175
Create Date: 2026-04-23 12:53:50.109664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daea903fc013'
down_revision: Union[str, None] = 'b3b3fe0e9175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('type', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('alerts', 'title')
    op.drop_column('alerts', 'is_active')
    op.add_column('blocks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_block_farm_name', 'blocks', ['farm_id', 'name'])
    op.add_column('egg_inventory', sa.Column('opening_stock', sa.Integer(), nullable=True))
    op.add_column('egg_inventory', sa.Column('received', sa.Integer(), nullable=True))
    op.add_column('egg_inventory', sa.Column('sold', sa.Integer(), nullable=True))
    op.add_column('egg_inventory', sa.Column('rejects', sa.Integer(), nullable=True))
    op.add_column('egg_inventory', sa.Column('breakages', sa.Integer(), nullable=True))
    op.add_column('egg_inventory', sa.Column('closing_stock', sa.Integer(), nullable=True))
    op.alter_column('egg_inventory', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_column('egg_inventory', 'good_eggs')
    op.drop_column('egg_inventory', 'total_eggs')
    op.drop_column('egg_inventory', 'bad_eggs')
    op.drop_column('egg_inventory', 'created_at')
    op.add_column('environment', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('environment', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('environment', sa.Column('ammonia', sa.Float(), nullable=True))
    op.add_column('environment', sa.Column('co2', sa.Float(), nullable=True))
    op.add_column('environment', sa.Column('light_intensity', sa.Float(), nullable=True))
    op.add_column('environment', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('environment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('environment', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('environment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('environment', 'recorded_at')
    op.drop_column('environment', 'light_intensity_lux')
    op.drop_column('environment', 'ammonia_ppm')
    op.drop_column('environment', 'co2_ppm')
    op.drop_column('environment', 'temperature_c')
    op.drop_column('environment', 'humidity_percent')
    op.add_column('feed_ingredients', sa.Column('stock_kg', sa.Float(), nullable=True))
    op.add_column('feed_ingredients', sa.Column('unit_cost', sa.Float(), nullable=True))
    op.alter_column('feed_ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('feed_ingredients', 'unit')
    op.drop_column('feed_ingredients', 'description')
    op.add_column('feed_inventory', sa.Column('feed_type', sa.String(), nullable=False))
    op.add_column('feed_inventory', sa.Column('opening_stock', sa.Float(), nullable=True))
    op.add_column('feed_inventory', sa.Column('received', sa.Float(), nullable=True))
    op.add_column('feed_inventory', sa.Column('consumed', sa.Float(), nullable=True))
    op.add_column('feed_inventory', sa.Column('closing_stock', sa.Float(), nullable=True))
    op.drop_constraint('feed_inventory_ingredient_id_fkey', 'feed_inventory', type_='foreignkey')
    op.drop_column('feed_inventory', 'created_at')
    op.drop_column('feed_inventory', 'expiry_date')
    op.drop_column('feed_inventory', 'date_received')
    op.drop_column('feed_inventory', 'ingredient_id')
    op.drop_column('feed_inventory', 'quantity')
    op.add_column('feed_mix_items', sa.Column('quantity_kg', sa.Float(), nullable=False))
    op.drop_column('feed_mix_items', 'percentage')
    op.add_column('feed_mixes', sa.Column('mix_date', sa.DateTime(), nullable=False))
    op.add_column('feed_mixes', sa.Column('total_kg', sa.Float(), nullable=False))
    op.add_column('feed_mixes', sa.Column('cost_per_kg', sa.Float(), nullable=False))
    op.alter_column('feed_mixes', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feed_mixes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('feed_mixes', 'description')
    op.add_column('notifications', sa.Column('read', sa.Boolean(), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'is_read')
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payments', 'stripe_payment_id')
    op.add_column('pens', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('pens', sa.Column('status', sa.String(), nullable=True))
    op.add_column('pens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('pens', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('pens', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pens', sa.Column('batch_name', sa.String(), nullable=True))
    op.add_column('pens', sa.Column('source_hatchery', sa.String(), nullable=True))
    op.add_column('pens', sa.Column('birds_per_kg', sa.Float(), nullable=True))
    op.add_column('pens', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('pens', sa.Column('floor_area_sq_m', sa.Float(), nullable=True))
    op.add_column('pens', sa.Column('max_density', sa.Float(), nullable=True))
    op.add_column('pens', sa.Column('litter_type', sa.String(), nullable=True))
    op.add_column('pens', sa.Column('feeder_count', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('waterer_count', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('nest_count', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('perch_length_cm', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('cell_length_mm', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('cell_width_mm', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('cell_height_mm', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('birds_per_cell', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('tiers_per_set', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('cells_per_set', sa.Integer(), nullable=True))
    op.add_column('pens', sa.Column('mortality_last_7d', sa.Integer(), nullable=True))
    op.alter_column('pens', 'housing_system',
               existing_type=postgresql.ENUM('BATTERY_CAGES', 'FLOOR_SYSTEM', 'DEEP_LITTER', 'FREE_RANGE', name='housingsystem'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('pens', 'initial_birds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pens', 'current_birds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('pens_created_by_fkey', 'pens', type_='foreignkey')
    op.create_foreign_key(None, 'pens', 'users', ['user_id'], ['id'])
    op.drop_column('pens', 'drinkers_count')
    op.drop_column('pens', 'feed_system')
    op.drop_column('pens', 'cages_per_cell')
    op.drop_column('pens', 'lighting_system')
    op.drop_column('pens', 'feeders_count')
    op.drop_column('pens', 'mortality')
    op.drop_column('pens', 'nests_count')
    op.drop_column('pens', 'birds_per_cage')
    op.drop_column('pens', 'age_weeks')
    op.drop_column('pens', 'created_by')
    op.drop_column('pens', 'cage_columns')
    op.drop_column('pens', 'ventilation_system')
    op.drop_column('pens', 'floor_area_sqft')
    op.drop_column('pens', 'cage_rows')
    op.drop_column('pens', 'water_system')
    op.drop_column('pens', 'perches_count')
    op.add_column('production_records', sa.Column('age_days', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('week_number', sa.Float(), nullable=True))
    op.add_column('production_records', sa.Column('opening_stock', sa.Integer(), nullable=False))
    op.add_column('production_records', sa.Column('closing_stock', sa.Integer(), nullable=False))
    op.add_column('production_records', sa.Column('mortality', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('feed_kg', sa.Float(), nullable=True))
    op.add_column('production_records', sa.Column('good_eggs', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('damaged_eggs', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('small_eggs', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('double_yolk_eggs', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('soft_shell_eggs', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('shells', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('broody_hen', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('culls', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('staff_name', sa.String(), nullable=True))
    op.add_column('production_records', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('production_records', sa.Column('total_eggs', sa.Integer(), nullable=True))
    op.add_column('production_records', sa.Column('hd_percentage', sa.Float(), nullable=True))
    op.add_column('production_records', sa.Column('er_ratio', sa.Float(), nullable=True))
    op.add_column('production_records', sa.Column('recorded_by_id', sa.Integer(), nullable=False))
    op.add_column('production_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('production_records', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('production_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('production_records_recorded_by_fkey', 'production_records', type_='foreignkey')
    op.create_foreign_key(None, 'production_records', 'users', ['recorded_by_id'], ['id'])
    op.drop_column('production_records', 'mortality_count')
    op.drop_column('production_records', 'eggs_laid')
    op.drop_column('production_records', 'recorded_by')
    op.drop_column('production_records', 'feed_consumed_kg')
    op.drop_column('production_records', 'water_consumed_liters')
    op.drop_column('production_records', 'eggs_collected')
    op.add_column('tray_inventory', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('tray_inventory', sa.Column('opening_stock', sa.Integer(), nullable=True))
    op.add_column('tray_inventory', sa.Column('received', sa.Integer(), nullable=True))
    op.add_column('tray_inventory', sa.Column('sold', sa.Integer(), nullable=True))
    op.add_column('tray_inventory', sa.Column('closing_stock', sa.Integer(), nullable=True))
    op.drop_column('tray_inventory', 'date_received')
    op.drop_column('tray_inventory', 'quantity')
    op.drop_column('tray_inventory', 'created_at')
    op.add_column('tray_sales', sa.Column('customer_name', sa.String(), nullable=False))
    op.add_column('tray_sales', sa.Column('trays', sa.Integer(), nullable=False))
    op.add_column('tray_sales', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('tray_sales', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('tray_sales', sa.Column('recorded_by_id', sa.Integer(), nullable=False))
    op.alter_column('tray_sales', 'sale_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('tray_sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('tray_sales_customer_id_fkey', 'tray_sales', type_='foreignkey')
    op.create_foreign_key(None, 'tray_sales', 'users', ['recorded_by_id'], ['id'])
    op.drop_column('tray_sales', 'total_amount')
    op.drop_column('tray_sales', 'quantity')
    op.drop_column('tray_sales', 'customer_id')
    op.add_column('users', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'SUPERVISOR', 'EGG_KEEPER', 'FEED_KEEPER', 'CUSTOMER', name='userrole'),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['reset_password_token'])
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'SUPERVISOR', 'EGG_KEEPER', 'FEED_KEEPER', 'CUSTOMER', name='userrole'),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'reset_password_expires')
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'contact')
    op.add_column('tray_sales', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tray_sales', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tray_sales', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tray_sales', type_='foreignkey')
    op.create_foreign_key('tray_sales_customer_id_fkey', 'tray_sales', 'users', ['customer_id'], ['id'])
    op.alter_column('tray_sales', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tray_sales', 'sale_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('tray_sales', 'recorded_by_id')
    op.drop_column('tray_sales', 'total_price')
    op.drop_column('tray_sales', 'currency')
    op.drop_column('tray_sales', 'trays')
    op.drop_column('tray_sales', 'customer_name')
    op.add_column('tray_inventory', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('tray_inventory', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tray_inventory', sa.Column('date_received', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('tray_inventory', 'closing_stock')
    op.drop_column('tray_inventory', 'sold')
    op.drop_column('tray_inventory', 'received')
    op.drop_column('tray_inventory', 'opening_stock')
    op.drop_column('tray_inventory', 'date')
    op.add_column('production_records', sa.Column('eggs_collected', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('production_records', sa.Column('water_consumed_liters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('production_records', sa.Column('feed_consumed_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('production_records', sa.Column('recorded_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('production_records', sa.Column('eggs_laid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('production_records', sa.Column('mortality_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'production_records', type_='foreignkey')
    op.create_foreign_key('production_records_recorded_by_fkey', 'production_records', 'users', ['recorded_by'], ['id'])
    op.alter_column('production_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_records', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('production_records', 'updated_at')
    op.drop_column('production_records', 'recorded_by_id')
    op.drop_column('production_records', 'er_ratio')
    op.drop_column('production_records', 'hd_percentage')
    op.drop_column('production_records', 'total_eggs')
    op.drop_column('production_records', 'image_url')
    op.drop_column('production_records', 'staff_name')
    op.drop_column('production_records', 'culls')
    op.drop_column('production_records', 'broody_hen')
    op.drop_column('production_records', 'shells')
    op.drop_column('production_records', 'soft_shell_eggs')
    op.drop_column('production_records', 'double_yolk_eggs')
    op.drop_column('production_records', 'small_eggs')
    op.drop_column('production_records', 'damaged_eggs')
    op.drop_column('production_records', 'good_eggs')
    op.drop_column('production_records', 'feed_kg')
    op.drop_column('production_records', 'mortality')
    op.drop_column('production_records', 'closing_stock')
    op.drop_column('production_records', 'opening_stock')
    op.drop_column('production_records', 'week_number')
    op.drop_column('production_records', 'age_days')
    op.add_column('pens', sa.Column('perches_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('water_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('cage_rows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('floor_area_sqft', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('ventilation_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('cage_columns', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pens', sa.Column('age_weeks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('birds_per_cage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('nests_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('mortality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('feeders_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('lighting_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('cages_per_cell', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('feed_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pens', sa.Column('drinkers_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pens', type_='foreignkey')
    op.create_foreign_key('pens_created_by_fkey', 'pens', 'users', ['created_by'], ['id'])
    op.alter_column('pens', 'current_birds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pens', 'initial_birds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pens', 'housing_system',
               existing_type=sa.String(),
               type_=postgresql.ENUM('BATTERY_CAGES', 'FLOOR_SYSTEM', 'DEEP_LITTER', 'FREE_RANGE', name='housingsystem'),
               nullable=False)
    op.drop_column('pens', 'mortality_last_7d')
    op.drop_column('pens', 'cells_per_set')
    op.drop_column('pens', 'tiers_per_set')
    op.drop_column('pens', 'birds_per_cell')
    op.drop_column('pens', 'cell_height_mm')
    op.drop_column('pens', 'cell_width_mm')
    op.drop_column('pens', 'cell_length_mm')
    op.drop_column('pens', 'perch_length_cm')
    op.drop_column('pens', 'nest_count')
    op.drop_column('pens', 'waterer_count')
    op.drop_column('pens', 'feeder_count')
    op.drop_column('pens', 'litter_type')
    op.drop_column('pens', 'max_density')
    op.drop_column('pens', 'floor_area_sq_m')
    op.drop_column('pens', 'notes')
    op.drop_column('pens', 'birds_per_kg')
    op.drop_column('pens', 'source_hatchery')
    op.drop_column('pens', 'batch_name')
    op.drop_column('pens', 'updated_at')
    op.drop_column('pens', 'start_date')
    op.drop_column('pens', 'user_id')
    op.drop_column('pens', 'status')
    op.drop_column('pens', 'capacity')
    op.add_column('payments', sa.Column('stripe_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('payments', 'stripe_payment_intent_id')
    op.drop_column('payments', 'payment_method')
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('notifications', 'read')
    op.add_column('feed_mixes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('feed_mixes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feed_mixes', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('feed_mixes', 'cost_per_kg')
    op.drop_column('feed_mixes', 'total_kg')
    op.drop_column('feed_mixes', 'mix_date')
    op.add_column('feed_mix_items', sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('feed_mix_items', 'quantity_kg')
    op.add_column('feed_inventory', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('feed_inventory', sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('feed_inventory', sa.Column('date_received', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('feed_inventory', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('feed_inventory', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('feed_inventory_ingredient_id_fkey', 'feed_inventory', 'feed_ingredients', ['ingredient_id'], ['id'])
    op.drop_column('feed_inventory', 'closing_stock')
    op.drop_column('feed_inventory', 'consumed')
    op.drop_column('feed_inventory', 'received')
    op.drop_column('feed_inventory', 'opening_stock')
    op.drop_column('feed_inventory', 'feed_type')
    op.add_column('feed_ingredients', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('feed_ingredients', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('feed_ingredients', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('feed_ingredients', 'unit_cost')
    op.drop_column('feed_ingredients', 'stock_kg')
    op.add_column('environment', sa.Column('humidity_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('environment', sa.Column('temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('environment', sa.Column('co2_ppm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('environment', sa.Column('ammonia_ppm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('environment', sa.Column('light_intensity_lux', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('environment', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('environment', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('environment', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.drop_column('environment', 'updated_at')
    op.drop_column('environment', 'notes')
    op.drop_column('environment', 'light_intensity')
    op.drop_column('environment', 'co2')
    op.drop_column('environment', 'ammonia')
    op.drop_column('environment', 'humidity')
    op.drop_column('environment', 'temperature')
    op.add_column('egg_inventory', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('egg_inventory', sa.Column('bad_eggs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('egg_inventory', sa.Column('total_eggs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('egg_inventory', sa.Column('good_eggs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('egg_inventory', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.drop_column('egg_inventory', 'closing_stock')
    op.drop_column('egg_inventory', 'breakages')
    op.drop_column('egg_inventory', 'rejects')
    op.drop_column('egg_inventory', 'sold')
    op.drop_column('egg_inventory', 'received')
    op.drop_column('egg_inventory', 'opening_stock')
    op.drop_constraint('uq_block_farm_name', 'blocks', type_='unique')
    op.drop_column('blocks', 'updated_at')
    op.add_column('alerts', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('alerts', 'is_resolved')
    op.drop_column('alerts', 'type')
    # ### end Alembic commands ###
